version: '3'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile.node
    volumes:
      - .:/app
    tty: true
    command: bash

  editor:
    build:
      context: .
      dockerfile: Dockerfile.editor
    tty: true
    volumes:
      - .:/app
    command: nvim
